version: "2.1"

services:
  motomuro:
    image: paolini/motomuro:latest
    restart: unless-stopped
    volumes:
      - ./logs:/logs
#    networks:
#      - backend
    ports:
      - 8992:8000

#networks:
#  backend:
#  web:
#    external: true
